// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_UvT9veRaNdm1ufwOnyQIAnOT0Z1gYo',
    appId: '1:731845041107:web:d27f78b6813d006a6fed26',
    messagingSenderId: '731845041107',
    projectId: 'foodgo-1b8c3',
    authDomain: 'foodgo-1b8c3.firebaseapp.com',
    storageBucket: 'foodgo-1b8c3.firebasestorage.app',
    measurementId: 'G-Z173B2WB4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTwS-xoe7apQ8WEvQ-C7M-nqhCi1uufw',
    appId: '1:731845041107:android:f846c93a04386bb56fed26',
    messagingSenderId: '731845041107',
    projectId: 'foodgo-1b8c3',
    storageBucket: 'foodgo-1b8c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzUOKiT7MCZ3tte3ZbGlPJa1rE8_wMGA',
    appId: '1:731845041107:ios:3516122f4b1d83626fed26',
    messagingSenderId: '731845041107',
    projectId: 'foodgo-1b8c3',
    storageBucket: 'foodgo-1b8c3.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrzUOKiT7MCZ3tte3ZbGlPJa1rE8_wMGA',
    appId: '1:731845041107:ios:3516122f4b1d83626fed26',
    messagingSenderId: '731845041107',
    projectId: 'foodgo-1b8c3',
    storageBucket: 'foodgo-1b8c3.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_UvT9veRaNdm1ufwOnyQIAnOT0Z1gYo',
    appId: '1:731845041107:web:4f49a981bca9fe3a6fed26',
    messagingSenderId: '731845041107',
    projectId: 'foodgo-1b8c3',
    authDomain: 'foodgo-1b8c3.firebaseapp.com',
    storageBucket: 'foodgo-1b8c3.firebasestorage.app',
    measurementId: 'G-3LKG94YMNN',
  );

}